Update pr-validation.yaml

diff --git a/.github/workflows/pr-validation.yaml b/.github/workflows/pr-validation.yaml
--- a/.github/workflows/pr-validation.yaml
+++ b/.github/workflows/pr-validation.yaml
@@ -9,17 +9,20 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Validate PR title
-        if: "!contains(github.event.pull_request.title, 'PSRE-')"
+        id: validate_title
         run: |
-          echo "PR title does not contain 'PSRE-'. Please include 'PSRE-' in the title."
-          exit 1
+          # Check if the PR title contains one of the specified JIRA keys followed by a number
+          if ! echo "${{ github.event.pull_request.title }}" | grep -qEi '^(PSREVCD|PSREVE|PSREDS|PSREADSYS|PSRE)-[0-9]+'; then
+            echo "PR title does not contain a valid JIRA key (PSREVCD, PSREVE, PSREDS, PSREADSYS, PSRE) followed by a number."
+            echo "::set-output name=valid::false"
+          else
+            echo "::set-output name=valid::true"
 
-  block_merge:
+  warn_invalid_title:
     runs-on: ubuntu-latest
-    needs: [validate_PR_title]
+    needs: validate_PR_title
+    if: needs.validate_PR_title.outputs.valid == 'false'
     steps:
-      - name: Block merge if PR title is invalid
-        if: failure()
+      - name: Warn about invalid PR title
         run: |
-          echo "::error::PR title does not contain 'PSRE-'. Please include 'PSRE-' in the title."
-          exit 1
+          echo "::warning title=Invalid PR Title::PR title does not contain a valid JIRA key (PSREVCD, PSREVE, PSREDS, PSREADSYS, PSRE) followed by a number. Please include a valid key and number in the title."
